#!/usr/bin/with-contenv bash
# spellcheck shell=bash

SMTPD_AUTH=${SMTPD_AUTH:-}
#SMTPD_LOG=${SMTP_LOG:-/config/log/msmtpd.log}
SMTPD_PORT=${SMTP_PORT:-25}

msmtpd_args=(
  --interface=0.0.0.0
  --port="${SMTPD_PORT}" 
  --log=/proc/self/fd/1
  #--log="${SMTPD_LOG}"
  # --command='/usr/bin/msmtp -f %F --'
)

if [[ ! -z ${SMTP_AUTH} ]]; then
  msmtpd_args+=(--auth="${SMTPD_AUTH}")
fi

if pgrep -f "/usr/bin/msmtpd" >/dev/null; then
  echo "Zombie MSMTPD process(es) detected, sending SIGTERM"
  pkill -ef "/usr/bin/msmtpd"
  sleep 1
fi

if pgrep -f "/usr/bin/msmtpd" >/dev/null; then
  echo "Zombie MSMTPD process(es) detected, sending SIGTERM"
  pkill -9 -ef "/usr/bin/msmtpd"
  sleep 1
fi

echo "Starting SMTP Server..."
set -ex
/usr/bin/msmtpd "${msmtpd_args[@]}"