#!/usr/bin/with-contenv bash

## The finish script is executed with four arguments:
#  1   the exit code from the run script (resp. 256 if the run script was killed by a signal)
#  2   an undefined number (resp. the number of the signal that killed the run script)
#  3   the name of the service directory, the same that has been given to ./run
#  4   the process group id of the defunct run script. This is useful to clean up services that leave children behind: 
#       for instance, if test "$1" -gt 255 ; then kill -9 -- -"$4" ; fi in the finish script will SIGKILL all children 
#       processes if the service crashed. This is not an entirely reliable mechanism, because an annoying service could 
#       spawn children processes in a different process group, but it should catch most offenders.

function signal() {
  case "$1" in
    "1")  echo "SIGHUP" ;;
    "2")  echo "SIGINT" ;;
    "3")  echo "SIGQUIT" ;;
    "4")  echo "SIGILL" ;;
    "5")  echo "SIGTRAP" ;;
    "6")  echo "SIGABRT" ;;
    "9")  echo "SIGKILL" ;;
    "10") echo "SIGUSR1" ;;
    "12") echo "SIGUSR2" ;;
    "14") echo "SIGALRM" ;;
    "15") echo "SIGTERM" ;;
    *) echo $((128 + $1))
  esac
  }

if test "$1" -eq 256; then
  code=$((128 + $2))
  reason="$(signal $2)"
else
  code="$1"
  reason="$1"
fi

echo "SMTP server has exited ($reason)..."
echo "$code" > /run/s6-linux-init-container-results/exitcode