#!/usr/bin/with-contenv bash
# spellcheck shell=bash

PID_FILE=/var/run/msmtpd.pid
SMTPD_AUTH=${SMTPD_AUTH:-}
SMTPD_PORT=${SMTP_PORT:-25}

function kill_zombies() {
  echo "Searching for zombie processes..."
  if pgrep -f "/usr/bin/msmtpd" >/dev/null; then
    echo "Zombie MSMTPD process(es) detected, sending SIGTERM"
    send_signal SIGTERM
    sleep 1
  fi

  if pgrep -f "/usr/bin/msmtpd" >/dev/null; then
    echo "Zombie MSMTPD process(es) detected, sending SIGKILL"
    send_signal SIGKILL
    sleep 1
  fi
  echo "Done"
}

function send_signal() {
  SIGNAL="${1:-SIGTERM}"
  echo "Sending ${SIGNAL} to msmtpd..."
  pkill -$SIGNAL -ef "/usr/bin/msmtpd"
}

function start() {
  msmtpd_args=(
    --interface=0.0.0.0
    --port="${SMTPD_PORT}" 
    --log=/proc/self/fd/1
    --command='/usr/bin/msmtp -C /config/msmtp.conf -d -f %F --'
  )

  if [[ ! -z ${SMTP_AUTH} ]]; then
    msmtpd_args+=(--auth="${SMTPD_AUTH}")
  fi

  echo "Starting SMTP Server..."
  exec s6-setuidgid abc /usr/bin/msmtpd "${msmtpd_args[@]}" 2>&1
}

kill_zombies
start
