name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  GHCR_SLUG: ghcr.io/dever23b/msmtpd

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.GHCR_SLUG }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=edge
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/bake-action@v7
        with:
          push: ${{ github.event_name != 'pull_request' }}
          targets: all
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
      - name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.GHCR_SLUG }}:${{ steps.meta.outputs.version }}
      - name: Inspect image
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.GHCR_SLUG }}:${{ steps.meta.outputs.version }}
          docker image inspect ${{ env.GHCR_SLUG }}:${{ steps.meta.outputs.version }}
